-- 1. Add a new generated column with a different name
-- Assuming that full_price exists and it's not generated
ALTER TABLE products ADD COLUMN full_price2 NUMERIC(10,2) 
  GENERATED BY DEFAULT AS (price * (1 + tax_rate)) STORED;

-- 2. Update existing records
UPDATE products SET full_price2 = full_price 
  WHERE full_price <> (price * (1 + tax_rate));

-- 3. Drop the old regular column
ALTER TABLE products DROP COLUMN full_price;

-- 4. Rename the new generated column to the old column's name
ALTER TABLE products RENAME COLUMN full_price2 TO full_price;

-- 5. Reclaim disk space
VACUUM FULL products;